//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.09.26 at 10:12:59 AM PDT 
//


package com.sri.bolt.xml;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for event.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="event">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="BOLT-BC-P2"/>
 *     &lt;enumeration value="BOLT-BOFFLINE-P2"/>
 *     &lt;enumeration value="BOLT-C-P2"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "event")
@XmlEnum
public enum Event {

    @XmlEnumValue("BOLT-BC-P2")
    BOLT_BC_P_2("BOLT-BC-P2"),
    @XmlEnumValue("BOLT-BOFFLINE-P2")
    BOLT_BOFFLINE_P_2("BOLT-BOFFLINE-P2"),
    @XmlEnumValue("BOLT-C-P2")
    BOLT_C_P_2("BOLT-C-P2");
    private final String value;

    Event(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static Event fromValue(String v) {
        for (Event c: Event.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
