//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.09.26 at 10:12:59 AM PDT 
//


package com.sri.bolt.xml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="audio" type="{}audioT" minOccurs="0"/>
 *         &lt;element name="text" type="{}textT" maxOccurs="2"/>
 *       &lt;/sequence>
 *       &lt;attribute name="button_pressed" use="required" type="{}relative_time" />
 *       &lt;attribute name="button_released" use="required" type="{}relative_time" />
 *       &lt;attribute name="asr_complete" use="required" type="{}relative_time" />
 *       &lt;attribute name="interrupt" type="{}interruptT" />
 *       &lt;attribute name="syscomment" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "audio",
    "text"
})
@XmlRootElement(name = "human_turn")
public class HumanTurn {

    protected AudioT audio;
    @XmlElement(required = true)
    protected List<TextT> text;
    @XmlAttribute(name = "button_pressed", required = true)
    protected String buttonPressed;
    @XmlAttribute(name = "button_released", required = true)
    protected String buttonReleased;
    @XmlAttribute(name = "asr_complete", required = true)
    protected String asrComplete;
    @XmlAttribute
    protected InterruptT interrupt;
    @XmlAttribute
    protected String syscomment;

    /**
     * Gets the value of the audio property.
     * 
     * @return
     *     possible object is
     *     {@link AudioT }
     *     
     */
    public AudioT getAudio() {
        return audio;
    }

    /**
     * Sets the value of the audio property.
     * 
     * @param value
     *     allowed object is
     *     {@link AudioT }
     *     
     */
    public void setAudio(AudioT value) {
        this.audio = value;
    }

    /**
     * Gets the value of the text property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the text property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getText().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TextT }
     * 
     * 
     */
    public List<TextT> getText() {
        if (text == null) {
            text = new ArrayList<TextT>();
        }
        return this.text;
    }

    /**
     * Gets the value of the buttonPressed property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getButtonPressed() {
        return buttonPressed;
    }

    /**
     * Sets the value of the buttonPressed property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setButtonPressed(String value) {
        this.buttonPressed = value;
    }

    /**
     * Gets the value of the buttonReleased property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getButtonReleased() {
        return buttonReleased;
    }

    /**
     * Sets the value of the buttonReleased property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setButtonReleased(String value) {
        this.buttonReleased = value;
    }

    /**
     * Gets the value of the asrComplete property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAsrComplete() {
        return asrComplete;
    }

    /**
     * Sets the value of the asrComplete property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAsrComplete(String value) {
        this.asrComplete = value;
    }

    /**
     * Gets the value of the interrupt property.
     * 
     * @return
     *     possible object is
     *     {@link InterruptT }
     *     
     */
    public InterruptT getInterrupt() {
        return interrupt;
    }

    /**
     * Sets the value of the interrupt property.
     * 
     * @param value
     *     allowed object is
     *     {@link InterruptT }
     *     
     */
    public void setInterrupt(InterruptT value) {
        this.interrupt = value;
    }

    /**
     * Gets the value of the syscomment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSyscomment() {
        return syscomment;
    }

    /**
     * Sets the value of the syscomment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSyscomment(String value) {
        this.syscomment = value;
    }

}
