//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.09.26 at 10:12:59 AM PDT 
//


package com.sri.bolt.xml;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for team.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="team">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="astral"/>
 *     &lt;enumeration value="delphi"/>
 *     &lt;enumeration value="fletcher"/>
 *     &lt;enumeration value="thunderbolt"/>
 *     &lt;enumeration value="bbn"/>
 *     &lt;enumeration value="ibm"/>
 *     &lt;enumeration value="saic"/>
 *     &lt;enumeration value="sri"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "team")
@XmlEnum
public enum Team {

    @XmlEnumValue("astral")
    ASTRAL("astral"),
    @XmlEnumValue("delphi")
    DELPHI("delphi"),
    @XmlEnumValue("fletcher")
    FLETCHER("fletcher"),
    @XmlEnumValue("thunderbolt")
    THUNDERBOLT("thunderbolt"),
    @XmlEnumValue("bbn")
    BBN("bbn"),
    @XmlEnumValue("ibm")
    IBM("ibm"),
    @XmlEnumValue("saic")
    SAIC("saic"),
    @XmlEnumValue("sri")
    SRI("sri");
    private final String value;

    Team(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static Team fromValue(String v) {
        for (Team c: Team.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
