package com.sri.bolt.workflow.task;

public enum WorkflowTaskType {
   AUDIO, FORCED_ALIGNMENT_EN, FORCED_ALIGNMENT_IA, OOV_EN, OOV_IA, CONF_SCORER, ANSWER_MERGER_EN, ANSWER_MERGER_IA, DIALOG_MANAGER_EN, DIALOG_MANAGER_IA, HOMOPHONE_DETECTOR_EN, HOMOPHONE_DETECTOR_IA, MT_ERROR_DETECTOR_EN,
   MT_ERROR_DETECTOR_IA, CLARIFICATION, EN_TRANSLATION, IA_TRANSLATION, ASR_ERROR_DETECTOR_IA, ASR_ERROR_DETECTOR_EN, SENSE_DETECTOR_EN, SENSE_DETECTOR_IA, TRANSLATION_PREPROCESS_EN,
   TRANSLATION_PREPROCESS_IA, NAME_DETECTOR_EN, NAME_DETECTOR_IA
}
